imoveisweb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('imvwb.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imvwb/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'imvwb'
urlpatterns = [
    path('', views.index, name='index'),
    path('casas/<int:casa_id>/', views.detail_casa, name='detail_casa'),
    path('apartamentos/<int:apto_id>/', views.detail_apto, name='detail_apto'),
    path('cadastro_casa/', views.cadastro_casa, name='cadastro_casa'),
    path('cadastro_apartamento/', views.cadastro_apto, name='cadastro_apto'),
    path('casas/', views.lista_casas, name='casas'),
    path('apartamentos/', views.lista_aptos, name='aptos'),
    path('contato', views.contato, name='contato'),
    path('entrar/', auth_views.LoginView.as_view(template_name='imvwb/entrar.html'), name='entrar')
]

imvwb/models.py
from django.db import models

# Create your models here.
class Bairro(models.Model):
    nome = models.CharField(max_length=30, blank=False)
    def __str__(self):
        return self.nome

class Imovel(models.Model):
    num_quartos = models.PositiveSmallIntegerField(blank=False)
    num_salas_estar = models.PositiveSmallIntegerField(blank=False)
    num_salas_jantar = models.PositiveSmallIntegerField(blank=False)
    area = models.PositiveSmallIntegerField(blank=False)
    num_vagas_garagem = models.PositiveSmallIntegerField(blank=False)
    possui_armario_embutido = models.BooleanField(default=False)
    descricao = models.TextField(max_length=500, blank=True)
    aluguel = models.PositiveIntegerField(blank=False)
    data_postagem = models.DateTimeField(auto_now_add=True)
    logradouro = models.CharField(max_length=50, blank=False)
    numero = models.PositiveSmallIntegerField(blank=False)
    bairro = models.ForeignKey(Bairro, on_delete=models.PROTECT)
    cidade = models.CharField(max_length=25, blank=False)
    uf = models.CharField(max_length=2, blank=False)

    def __str__(self):
        return "Imovel: {} nº {}, {}, {}, {}".format(self.logradouro, self.numero, self.bairro, self.cidade, self.uf)



class Casa(Imovel):
    def __str__(self):
        return "Casa: {} nº {}, {}, {}, {}".format(self.logradouro, self.numero, self.bairro, self.cidade, self.uf)

    pass

class Apartamento(Imovel):
    andar = models.PositiveSmallIntegerField(blank=False)
    valor_condominio = models.PositiveSmallIntegerField(blank=False)
    possui_portaria_24h = models.BooleanField(default=None)

    def __str__(self):
        return "Apartamento: {} nº {}, {}º andar, {}, {}, {}".format(self.logradouro, self.numero, self.andar, self.bairro, self.cidade, self.uf)

class Imagem(models.Model):
    imagem = models.ImageField(upload_to='images/')
    imovel = models.ForeignKey(Imovel, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.imagem.url)

imvwb/forms.py
from django import forms
from .models import Bairro

max_small_integer = 32767
max_positive_integer = 2147483647

class ImovelForm(forms.Form):
    tipo = None
    num_quartos = forms.IntegerField(label='Número de quartos', max_value=10)
    num_salas_estar = forms.IntegerField(label='Número de salas de estar', max_value=10)
    num_salas_jantar = forms.IntegerField(label='Número de salas de jantar', max_value=10)
    area = forms.IntegerField(label='Área (em m²)', max_value=max_small_integer)
    num_vagas_garagem = forms.IntegerField(label='Número de vagas de garagem', max_value=10)
    possui_armario_embutido = forms.BooleanField(label='Possui armário embutido?', required=False)
    
    logradouro = forms.CharField(label='Rua', max_length=100)
    numero = forms.CharField(label='Número', max_length=max_small_integer)
    bairro = forms.ModelChoiceField(label='Bairro', queryset=Bairro.objects.all())
    uf = forms.CharField(label='Unidade Federativa', max_length=2)
    cidade = forms.CharField(label='Cidade')
    aluguel = forms.IntegerField(label='Valor do aluguel', max_value=max_positive_integer)
    descricao = forms.CharField(label='Descricao', max_length=500, widget=forms.Textarea)

    imagens = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True, 'class':'form-control-file'}))


class CasaForm(ImovelForm):
    tipo = 1
    pass


class ApartamentoForm(ImovelForm):
    tipo = 2
    andar = forms.IntegerField(label='Andar', max_value=100)
    valor_condominio = forms.IntegerField(label='Valor do condomínio', max_value=max_small_integer)
    possui_portaria_24h = forms.BooleanField(label='Portaria 24h?', required=False)


class BairroForm(forms.Form):
    nome = forms.CharField(label='Nome', max_length=50)

imvwb/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

import datetime
from django.utils import timezone

from .models import Imovel, Casa, Apartamento, Imagem, Bairro
from .forms import BairroForm, CasaForm, ApartamentoForm
from .filters import ApartamentoFilter, CasaFilter
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import permission_required


# Create your views here.

def index(request):
    casas = Casa.objects.order_by('data_postagem')[:8]
    aptos = Apartamento.objects.order_by('data_postagem')[:8]

    now = timezone.now()
    one_week_ago = now-datetime.timedelta(7)

    for casa in casas:
        imagem = Imagem.objects.filter(imovel_id=casa.id)[0]
        casa.imagem = imagem.imagem
        casa.new=True if casa.data_postagem > one_week_ago else False


    for apto in aptos:
        imagem = Imagem.objects.filter(imovel_id=apto.id)[0]
        apto.imagem = imagem.imagem
        apto.new=True if casa.data_postagem > one_week_ago else False

    context = {
        'casas':casas,
        'aptos':aptos
    }
    return render(request, 'imvwb/index.html', context)

def contato(request):
    context = {}
    return render(request, 'imvwb/contato.html', context)

def detail_casa(request, casa_id):
    casa = get_object_or_404(Casa, pk=casa_id)
    imagens = Imagem.objects.filter(imovel=casa_id)

    print(imagens)
    context = {'casa': casa, 'imagens': imagens}

    return render(request, 'imvwb/detail_casa.html', context)

def detail_apto(request, apto_id):
    apto = get_object_or_404(Apartamento, pk=apto_id)
    imagens = Imagem.objects.filter(imovel=apto_id)
    context = {'apto': apto, 'imagens': imagens}

    return render(request, 'imvwb/detail_apto.html', context)




@permission_required("imvwb.add_casa")
def cadastro_casa(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST' and 'btnImovel' in request.POST:
        # create a form instance and populate it with data from the request:
        form = CasaForm(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            # Se o form for valido, cadastrar a Casa
            num_quartos = form.cleaned_data['num_quartos']
            num_salas_estar = form.cleaned_data['num_salas_estar']
            num_salas_jantar = form.cleaned_data['num_salas_jantar']
            area = form.cleaned_data['area']
            num_vagas_garagem = form.cleaned_data['num_vagas_garagem']
            possui_armario_embutido = form.cleaned_data['possui_armario_embutido']
            
            logradouro = form.cleaned_data['logradouro']
            numero = form.cleaned_data['numero']
            bairro = form.cleaned_data['bairro']
            uf = form.cleaned_data['uf']
            cidade = form.cleaned_data['cidade']
            aluguel = form.cleaned_data['aluguel']
            descricao = form.cleaned_data['descricao']

            casa = Casa(
                num_quartos = num_quartos,
                num_salas_estar = num_salas_estar,
                num_salas_jantar = num_salas_jantar,
                area = area,
                num_vagas_garagem = num_vagas_garagem,
                possui_armario_embutido = possui_armario_embutido,
                descricao = descricao,
                aluguel = aluguel,
                logradouro = logradouro,
                numero = numero,
                bairro = bairro,
                cidade = cidade,
                uf = uf,
            )

            casa.save()
            files = request.FILES.getlist('imagens')
            imovel = Imovel.objects.get(pk=casa.id)

            for img in files:
                # Apos ter criado a casa, cadastrar cada imagem - com a PK da casa
                
                img_objeto = Imagem(
                        imagem = img,
                        imovel = imovel
                )
                img_objeto.save()
            
            return HttpResponseRedirect(reverse('imvwb:index'))

    elif request.method == 'POST' and 'btnBairro' in request.POST:
        # create a form instance and populate it with data from the request:
        formBairro = BairroForm(request.POST)
        
        # check whether it's valid:
        if formBairro.is_valid():
            nome = formBairro.cleaned_data['nome']

            bairro = Bairro(
                nome = nome
            )
            bairro.save()
            
            return HttpResponseRedirect(request.path_info)

    # if a GET (or any other method) we'll create a blank form
    else:
        context = {
        'form':CasaForm(),
        'formBairro':BairroForm()
        }

    return render(request, 'imvwb/cadastro_imovel.html', context)

@permission_required("imvwb.add_apartamento")
def cadastro_apto(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST' and 'btnImovel' in request.POST:
        # create a form instance and populate it with data from the request:
        form = ApartamentoForm(request.POST, request.FILES)
        
        # check whether it's valid:
        if form.is_valid():
            # Se o form for valido, cadastrar a Casa
            num_quartos = form.cleaned_data['num_quartos']
            num_salas_estar = form.cleaned_data['num_salas_estar']
            num_salas_jantar = form.cleaned_data['num_salas_jantar']
            area = form.cleaned_data['area']
            num_vagas_garagem = form.cleaned_data['num_vagas_garagem']
            possui_armario_embutido = form.cleaned_data['possui_armario_embutido']
            
            logradouro = form.cleaned_data['logradouro']
            numero = form.cleaned_data['numero']
            bairro = form.cleaned_data['bairro']
            uf = form.cleaned_data['uf']
            cidade = form.cleaned_data['cidade']
            aluguel = form.cleaned_data['aluguel']
            descricao = form.cleaned_data['descricao']


            andar = form.cleaned_data['andar']
            valor_condominio = form.cleaned_data['valor_condominio']
            possui_portaria_24h = form.cleaned_data['possui_portaria_24h']


            apto = Apartamento(
                num_quartos = num_quartos,
                num_salas_estar = num_salas_estar,
                num_salas_jantar = num_salas_jantar,
                area = area,
                num_vagas_garagem = num_vagas_garagem,
                possui_armario_embutido = possui_armario_embutido,
                descricao = descricao,
                aluguel = aluguel,
                logradouro = logradouro,
                numero = numero,
                bairro = bairro,
                cidade = cidade,
                uf = uf,
                andar = andar,
                valor_condominio = valor_condominio,
                possui_portaria_24h = possui_portaria_24h
            )

            apto.save()
            files = request.FILES.getlist('imagens')
            imovel = Imovel.objects.get(pk=apto.id)

            for img in files:
                # Apos ter criado o apto, cadastrar cada imagem - com a PK do apto
                img_objeto = Imagem(
                        imagem = img,
                        imovel = imovel
                )
                img_objeto.save()
            
            return HttpResponseRedirect(reverse('imvwb:index'))
    
    elif request.method == 'POST' and 'btnBairro' in request.POST:
        # create a form instance and populate it with data from the request:
        formBairro = BairroForm(request.POST)
        
        # check whether it's valid:
        if formBairro.is_valid():
            nome = formBairro.cleaned_data['nome']

            bairro = Bairro(
                nome = nome
            )
            bairro.save()
            
            return HttpResponseRedirect(request.path_info)

    # if a GET (or any other method) we'll create a blank form
    else:
        context = {
        'form':ApartamentoForm(),
        'formBairro':BairroForm()
        }

    return render(request, 'imvwb/cadastro_imovel.html', context)

def lista_casas(request):
    casas_list = Casa.objects.order_by('data_postagem')
    casa_filter = CasaFilter(request.GET, queryset=casas_list)
    now = timezone.now()
    one_week_ago = now-datetime.timedelta(7)

    for casa in casa_filter.qs:
        imagem = Imagem.objects.filter(imovel_id=casa.id)[0]
        casa.imagem = imagem.imagem
        casa.new=True if casa.data_postagem > one_week_ago else False
    
    context = {
        'casas':casa_filter.qs,
        'form':casa_filter.form,
    }

    return render(request, 'imvwb/lista_casas.html', context)

def lista_aptos(request):
    aptos_list = Apartamento.objects.order_by('data_postagem')
    apto_filter = ApartamentoFilter(request.GET, queryset=aptos_list)

    now = timezone.now()
    one_week_ago = now-datetime.timedelta(7)

    for apto in apto_filter.qs:
        imagem = Imagem.objects.filter(imovel_id=apto.id)[0]
        apto.imagem = imagem.imagem
        apto.new=True if apto.data_postagem > one_week_ago else False
    
    context = {
        'aptos':apto_filter.qs,
        'form':apto_filter.form,
    }

    return render(request, 'imvwb/lista_aptos.html', context)

imvwb/templates/imvwb/base.html
<html lang="en" class="h-100">

  <!-- CSS only -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
 
  <style>
    .card-img-top {
      width: 100%;
      height: 10vw;
      object-fit: cover;
  }
  </style>

  {% load imvwb_extras %}
  {% load static %}

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand px-0 py-0 mx-0" href="{% url 'imvwb:index'  %}" style="width:175px">
        <img src="{% static "imvwb/images/umlugar.png" %}" style="width:100%" class="d-inline-block align-top" alt="umlugar imóveis">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'imvwb:index'  %}">Página Inicial<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'imvwb:aptos'  %}">Apartamentos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'imvwb:casas'  %}">Casas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'imvwb:contato'  %}">Contato</a>
          </li>
          {% if user.is_authenticated %}
            {% if request.user|has_group:"Vendas" %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Cadastrar
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'imvwb:cadastro_casa'  %}">Casa</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'imvwb:cadastro_apto'  %}">Apartamento</a>
              </div>
            </li>
            {% endif %}
          {% endif %}
        </ul>
      </div>

      {% if user.is_authenticated %}
        <a class="btn btn-outline-secondary" href="{% url 'logout'  %}" role="button">{{ user.get_username }} | sair</a> 
      {% else %}
        <a class="nav-link my-2 my-sm-0" href="{% url 'login'  %}">Entrar</a>  
      {% endif %}
    </nav>


    <div class="container pt-4">
        {% block content %}
        {% endblock %}
    </div>


    <footer class="footer mt-auto py-3">
      <div class="container">
        <span class="text-muted">Gustavo Brito e Samir Saliba, Setembro de 2020</span>
      </div>
    </footer>


  <!-- JS, Popper.js, and jQuery -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  
  </body>

</html>

imvwb/templates/imvwb/contato.html
{% extends "./base.html" %} 
{% block content %}

<script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>

<div class=row>
    <div class="col">
        <h3>Contato</h3>
    </div>

    <div class="col">
        <h3>Sobre</h3>
    </div>
</div>

<div class="row justify-content-md-center">
    <div class="col">
        <div class="LI-profile-badge"  data-version="v1" data-size="large" data-locale="pt_BR" data-type="vertical" data-theme="light" data-vanity="samirtsj">
            <a class="LI-simple-link" href='https://br.linkedin.com/in/samirtsj?trk=profile-badge'>Samir Saliba Junior</a>
        </div>
    </div>
    <div class="col">
        <p class="lead text-justify">
            Trabalho feito para a disciplina de Engenharia de Software, ministrada pelo professor doutor Eduardo Campos Cunha.
            Por Samir Saliba Jr e Gustavo Brito.
            <br>
            <p class="text-muted text-right"><abbr title="Centro Federal de Educação Tecnológica de Minas Gerais" class="initialism">CEFET-MG</abbr>, Setembro de 2020</p> 
        </p>

    </div>
</div>




{% endblock %}

imvwb/templates/imvwb/entrar.html
{% extends "./base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

imvwb/templates/imvwb/index.html
{% extends "./base.html" %} 
{% block content %}


<div class="row">
    <h3>
        <a href="{% url 'imvwb:casas' %}" class="text-decoration-none">
        Casas
        </a>
    </h3>
</div>

<div class="row pb-4">
    {% for casa in casas %}
        <div class="col-3 px-0">
            <div class="card" style="width:100%">
                <img src="{{casa.imagem.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'imvwb:detail_casa' casa.id %}" class="text-decoration-none">
                            Casa em {{casa.bairro}}, {{casa.cidade}}, {{casa.area}} m²
                        </a>
                    </h5>
                    <p class="card-text">{{casa.num_quartos}} Quartos</p>
                    <h5>
                        <span class="badge badge-success badge-pill">R${{casa.aluguel}}</span>
                        {%if casa.new %}
                            <span class="badge badge-secondary badge-pill">Novidade</span>
                        {% endif %}
                    </h5>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

<div class="row">
    <h3>
        <a href="{% url 'imvwb:aptos' %}" class="text-decoration-none">
           Apartamentos
        </a>
    </h3>
</div>


<div class="row">
    {% for apto in aptos %}
        <div class="col-3 px-0">
            <div class="card mx-0" style="width:100%">
                <img src="{{apto.imagem.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'imvwb:detail_apto' apto.id %}" class="text-decoration-none">
                            Apartamento em {{apto.bairro}}, {{apto.cidade}}, {{apto.area}} m²
                        </a>
                    </h5>
                    <p class="card-text">{{apto.num_quartos}} Quartos</p>
                    <h5>
                        <span class="badge badge-success badge-pill">R${{apto.aluguel}}</span>
                        {%if apto.new %}
                            <span class="badge badge-secondary badge-pill">Novidade</span>
                        {% endif %}
                    </h5>
                </div> 
            </div>
        </div>
    {% endfor %}
</div>


{% endblock %}

imvwb/templates/imvwb/lista_aptos.html
{% extends "./base.html" %} 
{% block content %}

<div class="row">
    <h3>
        <a href="{% url 'imvwb:aptos' %}" class="text-decoration-none">
           Apartamentos
        </a>
    </h3>
</div>

<div class="row">
    <div class="jumbotron w-100">
        <form method="get" id="getForm">
            <div class="row pb-3">
                <div class="col">
                    <div class="input-group mb-3">
                        {{ form.aluguel__gt.errors }}
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="{{form.aluguel__gt.id_for_label}}">Aluguel mínimo</span>
                        </div>
                        {{ form.aluguel__gt }}
                    </div>
                </div>
                <div class="col">
                    <div class="input-group mb-3">
                        {{ form.aluguel__lt.errors }}
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="{{ form.aluguel__lt.id_for_label }}">Aluguel máximo</span>
                        </div>
                        {{ form.aluguel__lt }}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class='col-md-6'>
                    <div class="input-group mb-4">
                        {{ form.bairro.errors }}
                        <div class="input-group-prepend">
                        <label class="input-group-text" for="{{form.bairro.id_for_label}}">Bairro</label>
                        </div>
                        {{ form.bairro }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-group mb-3">
                        {{ form.quartos__gt.errors }}
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="{{form.quartos__gt.id_for_label}}">Nº quartos mínimo</span>
                        </div>
                        {{ form.quartos__gt }}
                    </div>
                </div>
            </div>
            <button type="submit" for="getForm" class="btn btn-primary">Filtrar</button>
        </form>
    </div>
</div>


<div class="row">
    {% for apto in aptos %}
        <div class="col-3 px-0">
            <div class="card mx-0" style="width:100%">
                <img src="{{apto.imagem.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'imvwb:detail_apto' apto.id %}" class="text-decoration-none">
                            Apartamento em {{apto.bairro}}, {{apto.cidade}}, {{apto.area}} m²
                        </a>
                    </h5>
                    <p class="card-text">{{apto.num_quartos}} Quartos</p>
                    <h5>
                        <span class="badge badge-success badge-pill">R${{apto.aluguel}}</span>
                        {%if apto.new %}
                            <span class="badge badge-secondary badge-pill">Novidade</span>
                        {% endif %}
                    </h5>
                </div> 
            </div>
        </div>
    {% endfor %}
</div>

  
{% endblock %}

imvwb/templates/imvwb/lista_casas.html
{% extends "./base.html" %} 
{% block content %}

<div class="row">
    <h3>
        <a href="{% url 'imvwb:casas' %}" class="text-decoration-none">
        Casas
        </a>
    </h3>
</div>


<div class="row">
    <div class="jumbotron w-100">
        <form method="get" id="getForm">
            <div class="row pb-3">
                <div class="col">
                    <div class="input-group mb-3">
                        {{ form.aluguel__gt.errors }}
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="{{form.aluguel__gt.id_for_label}}">Aluguel mínimo</span>
                        </div>
                        {{ form.aluguel__gt }}
                    </div>
                </div>
                <div class="col">
                    <div class="input-group mb-3">
                        {{ form.aluguel__lt.errors }}
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="{{ form.aluguel__lt.id_for_label }}">Aluguel máximo</span>
                        </div>
                        {{ form.aluguel__lt }}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class='col-md-6'>
                    <div class="input-group mb-4">
                        {{ form.bairro.errors }}
                        <div class="input-group-prepend">
                        <label class="input-group-text" for="{{form.bairro.id_for_label}}">Bairro</label>
                        </div>
                        {{ form.bairro }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-group mb-3">
                        {{ form.quartos__gt.errors }}
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="{{form.quartos__gt.id_for_label}}">Nº quartos mínimo</span>
                        </div>
                        {{ form.quartos__gt }}
                    </div>
                </div>
            </div>
            <button type="submit" for="getForm" class="btn btn-primary">Filtrar</button>
        </form>
    </div>
</div>

<div class=row>
    {% for casa in casas %}
        <div class="col-3 px-0">
            <div class="card" style="width:100%">
                <img src="{{casa.imagem.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'imvwb:detail_casa' casa.id %}" class="text-decoration-none">
                            Casa em {{casa.bairro}}, {{casa.cidade}}, {{casa.area}} m²
                        </a>
                    </h5>
                    <p class="card-text">{{casa.num_quartos}} Quartos</p>
                    <h5>
                        <span class="badge badge-success badge-pill">R${{casa.aluguel}}</span>
                        {%if casa.new %}
                            <span class="badge badge-secondary badge-pill">Novidade</span>
                        {% endif %}
                    </h5>
                </div>
            </div>
        </div>
    {% endfor %}
</div>


{% endblock %}