imoveisweb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('imvwb.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imvwb/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'imvwb'
urlpatterns = [
    path('', views.index, name='index'),
    path('casas/<int:casa_id>/', views.detail_casa, name='detail_casa'),
    path('apartamentos/<int:apto_id>/', views.detail_apto, name='detail_apto'),
    path('cadastro_casa/', views.cadastro_casa, name='cadastro_casa'),
    path('cadastro_apartamento/', views.cadastro_apto, name='cadastro_apto'),
    path('casas/', views.lista_casas, name='casas'),
    path('apartamentos/', views.lista_aptos, name='aptos'),
    path('contato', views.contato, name='contato'),
    path('entrar/', auth_views.LoginView.as_view(template_name='imvwb/entrar.html'), name='entrar')
]

templates/base.html
<!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Imóveis Web</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'imvwb:index'  %}">Página Inicial<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'imvwb:aptos'  %}">Apartamentos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'imvwb:casas'  %}">Casas</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'imvwb:contato'  %}">Contato | Sobre Nós</a>
        </li>
      </ul>
    </div>
</nav>


<div class="container pt-5">
    {% block content %}
    {% endblock %}
</div>



<footer class="footer">
  <div class="container">
    <span class="text-muted">2020, Gustavo Brito e Samir Saliba</span>
  </div>
</footer>